name: Auto_Package

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Package with Node
        env:
          CHROME_PEM: ${{ secrets.CHROME_PEM }}
        run: |
          echo "$CHROME_PEM" > ./build/cxmooc-tools.pem
          chmod 600 ./build/cxmooc-tools.pem
          npm ci
          npm test
          npm run build
          npm run build-tampermonkey
          npm run pack

      - name: ZIP files
        run: |
          cd build/cxmooc-tools && zip ../cxmooc-tools.zip -r ./ && cd ../../

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          body: |
            'no description'
          draft: false
          prerelease: false
          name: cxmooc-tools-${{ github.ref }}
          tag_name: ${{ github.ref }}
          files: |
            ./build/cxmooc-tools.zip
            ./build/cxmooc-tools.crx
